import xlsxwriter

# data will be generated by iterating over the product data object for each # product in the export list and getting the highest number for each field # being exported

data = {  # these values represent populated fields where
    # more fields are available but empty
    'data_one': 1,
    'data_two': 1,
    'data_three': 4,
    'data_four': 1,
    'data_five': 1,
    'data_six': 2,
    'data_seven': 1,
    'data_eight': 4,
    'data_nine': 1,
    'data_ten': 1,
    'data_eleven': 1,
    'data_twelve': 1,
    'data_thirteen': 1, 
    'data_fourteen': 1
}


def main(input_data):
    workbook = xlsxwriter.Workbook('123.xlsx')
    worksheet = workbook.add_worksheet('walmart enterprise')
    bold = workbook.add_format({'bold': 1})
    xls_header = input_data.keys()
    xls_header.sort()
    xls_data = []
    xls_data.append(xls_header)
    row_data = []
    for item in xls_header:
        row_data.append(input_data[item])
    xls_data.append(row_data)
    for row, each in enumerate(xls_data):
        for col,item in enumerate(each):
            worksheet.write(row, col, item, bold)

    workbook.close()




if __name__ == "__main__":
    main(data)
